### ISSUE TITLE
Add ability to manually set DOOM WAD file in Python options

### ISSUE THREAD

**Issue by lunrsh** [wojciech-graj/cydoomgeneric#3]
# Summary
I'd like the ability to manually set either the WAD file's data (a list of some sort?) or the file path to use. I would say manually setting the WAD's data would be useful to more people, but if you can only control the file path, that's fine.  

This might already be in there, but I couldn't find it when I was looking through the source code.

**Comment by wojciech-graj** [comment]
This is currently possible with the `-iwad` command-line argument that can be passed to `cdg.main`.

```python
cdg.main(argv=["cydoomgeneric", "-iwad", "your/wad/file.wad"])
```
